### ISSUE TITLE
Request: adding items picture in the rss feed

### ISSUE THREAD

**Issue by wokawoka** [adamxp12/FeedBay#3]
Would it be possible to include the ebay item pictures in the rss feed?
They would be very useful while going through many items in the article list.
Thank you!

**Comment by adamxp12** [comment]
Images are already included. Just tested with ebay UK and ebay US and its working fine.

However the images are in the description as HTML. This replicates the original RSS design that ebay used before. 

I did consider using the official RSS <image> tag but then it would not be 100% like the service it replaced and chose to retain feature parity over making it technically correct.

If you however have an issue with a specific search not providing images? Feel free to reply

**Comment by wokawoka** [comment]
Yes, you are right, sorry.
I checked the generated feed and the pictures addresses are there. 
It was probably an issue of the rss reader I did test the feed with (Rss guard on linux), I just tested the feed again with another client (fluent reader) and the images are there .
Thank you again for this very useful piece of software!
